# Generated by Django 2.0.6 on 2019-05-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
